version: '3'
services:
  web:
    image: nginx:latest
    container_name: rs-web
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./services/nginx/logs:/var/log/nginx/
      - ./www:/var/www/
    ports:
      - "8002:80"

  mongodb:
    image: mongo
    container_name: rs-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: rsuser
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_RSUSER_PASSWORD}
      MONGO_INITDB_DATABASE: rsdb
    ports:
      - "27017:27017"
    volumes:
      - ./services/mongodb:/data/db

  nodejs:
    build:
      context: ./services/nodejs
      dockerfile: Dockerfile
    container_name: rs-nodejs
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  node_modules:
