name: Deploy to S3 and EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     # - name: Set up AWS CLI
     #   uses: aws-actions/configure-aws-credentials@v1
     #   with:
     #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
     #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     #     aws-region: us-east-1
#
     # - name: Sync files to S3 bucket
     #   run: aws s3 sync . s3://exerhub --delete

      - name: Sync files to EC2 instance
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          rsync -avz --exclude 'mongodb' --exclude 'private_key.pem' --exclude 'logs' --exclude 'node_modules' --exclude 'certbot' --exclude 'package-lock.json' -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" --delete ./ ubuntu@44.199.76.209:/home/ubuntu/yoho/
          rm -f private_key.pem
